
words = [
    "Tiger", "Bicycle", "Rainbow", "Elephant", "Candle", "Ocean", "Piano", "Mango", "Telescope", "Cloud", "Rachmaninoff",
    "Mountain", "Lemon", "Galaxy", "Fireworks", "Laptop", "Butterfly", "Moon", "Pineapple", "Waterfall", "Guitar",
    "Dragon", "Diamond", "Forest", "Sunflower", "Ice cream", "Starfish", "Camera", "Chocolate", "Satellite", "Raincoat",
    "Coffee", "Squirrel", "Compass", "Dolphin", "Bookshelf", "Watermelon", "Cactus", "Hot air balloon", "Thunderstorm",
    "Violin", "Kangaroo", "Backpack", "Lightning", "Castle", "Flamingo", "Microphone", "Bubble", "Penguin", "Hammock",
    "Saxophone", "Zebra", "Paintbrush", "Jellyfish", "Sombrero", "Cherry", "Cruise", "Turtle", "Suitcase", "Seashell",
    "Pinecone", "Basketball", "Coconut", "Sailboat", "Lavender", "Snowflake", "Giraffe", "Popcorn", "Seagull", "Palm tree",
    "Helicopter", "Bumblebee", "Trampoline", "Firefly", "Banana", "Caramel", "Ostrich", "Fountain", "Pretzel", "Koala",
    "Baguette", "Tornado", "Snowman", "Frisbee", "Campfire", "Avocado", "Toucan", "Chameleon", "Lighthouse", "Popsicle",
    "Seahorse", "Raspberry", "Hammer", "Cheetah", "Snowboard", "Cookie", "Bamboo", "Binoculars", "Sandcastle", "Crocodile",
    "Volcano", "Blueberry", "Panda", "Suitcase", "Raincoat", "Microphone", "Bookshelf", "Watermelon", "Palm tree", "Rainbow",
    "Telescope", "Backpack", "Laptop", "Zebra", "Penguin", "Seashell", "Flamingo", "Banana", "Butterfly", "Hot air balloon",
    "Moonlight", "Cherry", "Guitar", "Pineapple", "Cruise", "Cactus", "Waterfall", "Kangaroo", "Chameleon", "Popsicle",
    "Raincoat", "Lighthouse", "Fireworks", "Saxophone", "Helicopter", "Tornado", "Jellyfish", "Galaxy", "Pretzel", "Watermelon",
    "Cherry", "Caramel", "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain",
    "Cherry", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Piano", "Firefly", "Violin", "Panda",
    "Seashell", "Palm tree", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Suitcase",
    "Raincoat", "Microphone", "Bookshelf", "Watermelon", "Palm tree", "Telescope", "Backpack", "Laptop", "Zebra", "Penguin",
    "Seashell", "Flamingo", "Banana", "Butterfly", "Hot air balloon", "Moonlight", "Cherry", "Guitar", "Pineapple",
    "Cruise", "Cactus", "Waterfall", "Kangaroo", "Chameleon", "Popsicle", "Raincoat", "Lighthouse", "Fireworks", "Saxophone",
    "Helicopter", "Tornado", "Jellyfish", "Galaxy", "Pretzel", "Watermelon", "Cherry", "Caramel", "Seagull", "Telescope",
    "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Cherry", "Paintbrush", "Flamingo", "Basketball",
    "Butterfly", "Starfish", "Piano", "Firefly", "Violin", "Panda", "Seashell", "Palm tree", "Dragon", "Lemon",
    "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Fireworks", "Saxophone", "Helicopter",
    "Tornado", "Jellyfish", "Galaxy", "Pretzel", "Watermelon", "Cherry", "Caramel", "Seagull", "Telescope", "Hammock",
    "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish",
    "Piano", "Firefly", "Violin", "Panda", "Seashell", "Palm tree", "Dragon", "Lemon", "Dolphin", "Sailboat",
    "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Fireworks", "Saxophone", "Helicopter", "Tornado", "Jellyfish",
    "Galaxy", "Pretzel", "Watermelon", "Caramel", "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot",
    "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Piano", "Violin", "Panda",
    "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse",
    "Fireworks", "Saxophone", "Tornado", "Jellyfish", "Galaxy", "Pretzel", "Watermelon", "Caramel", "Seagull", "Telescope",
    "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly",
    "Starfish", "Piano", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe",
    "Rainbow", "Chocolate", "Lighthouse", "Fireworks", "Saxophone", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel",
    "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo",
    "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone",
    "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Fireworks", "Saxophone", "Tornado", "Jellyfish", "Galaxy", "Watermelon",
    "Caramel", "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush",
    "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat",
    "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Fireworks", "Tornado", "Jellyfish", "Galaxy", "Watermelon",
    "Caramel", "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush",
    "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat",
    "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel",
    "Seagull", "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo",
    "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone",
    "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull",
    "Telescope", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball",
    "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe",
    "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock",
    "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish",
    "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate",
    "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock", "Moon", "Microphone",
    "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell",
    "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado",
    "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm",
    "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon",
    "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy",
    "Watermelon", "Caramel", "Seagull", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush",
    "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat",
    "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel",
    "Seagull", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball",
    "Butterfly", "Starfish", "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe",
    "Rainbow", "Chocolate", "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock",
    "Moon", "Microphone", "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish",
    "Violin", "Seashell", "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate",
    "Lighthouse", "Tornado", "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock", "Moon", "Microphone",
    "Parrot", "Thunderstorm", "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell",
    "Dragon", "Lemon", "Dolphin", "Sailboat", "Pinecone", "Giraffe", "Rainbow", "Chocolate", "Lighthouse", "Tornado",
    "Jellyfish", "Galaxy", "Watermelon", "Caramel", "Seagull", "Hammock", "Moon", "Microphone", "Parrot", "Thunderstorm",
    "Mountain", "Paintbrush", "Flamingo", "Basketball", "Butterfly", "Starfish", "Violin", "Seashell", "Dragon"]

words = list(set(words))
print(words)
